name = "Casper"
description = "The port of Ghost's Casper theme"
license = "MIT"
homepage = "https://github.com/Leo1003/zola-casper"
# The minimum version of Zola required
min_version = "0.15.0"
# An optional live demo URL
#demo = ""

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
default_authors = []

navigation = []

navigation_secondary = []

[extra.design]
# Possible value: sans-serif, serif
title_font = "sans-serif"

# Possible value: sans-serif, serif
body_font = "serif"

# Possible value: None, Medium, Large
publication_cover_style = "Medium"

publication_cover_image = ""

# Possible value: Dynamic_Grid, Simple_Grid, List
feed_layout = "Dynamic_Grid"

# Possible value: Auto, Light, Dark
color_scheme = "Light"

#header_button_background = "#ffffff"

# Possible value: Light, Dark
header_button_text_color = "Light"

# Possible value: Wide, Full, Small
post_image_width = "Wide"

show_recent_posts = true

[extra.social]
#facebook = "https://www.facebook.com"
#twitter = "https://www.twitter.com"